services:
  frontend:   
    restart: unless-stopped
    container_name: school_mgmt_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: school_mgmt/frontend:1.0.0
    ports:
      - "5173:5173"
    volumes:
      - .:/home/node/frontend
    networks:
      - school_mgmt_network
    environment:
      NODE_ENV: production
      VITE_API_URL: http://school_mgmt_backend:5007
      VITE_APP_NAME: Student Management System
      VITE_APP_VERSION: 1.0.0
  backend:
    restart: unless-stopped
    container_name: school_mgmt_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: school_mgmt/backend:1.0.0
    ports:
      - "5007:5007"
    volumes:
      - .:/home/node/backend
    networks:
      - school_mgmt_network
    environment:
      NODE_ENV: production
      PORT: 5007
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@school_mgmt_postgres:${DB_PORT}/${DB_NAME}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      CSRF_TOKEN_SECRET: ${CSRF_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_TIME_IN_MS: ${JWT_ACCESS_TOKEN_TIME_IN_MS}
      JWT_REFRESH_TOKEN_TIME_IN_MS: ${JWT_REFRESH_TOKEN_TIME_IN_MS}
      CSRF_TOKEN_TIME_IN_MS: ${CSRF_TOKEN_TIME_IN_MS}
      MAIL_FROM_USER: ${MAIL_FROM_USER}
      EMAIL_VERIFICATION_TOKEN_SECRET: ${EMAIL_VERIFICATION_TOKEN_SECRET}
      EMAIL_VERIFICATION_TOKEN_TIME_IN_MS: ${EMAIL_VERIFICATION_TOKEN_TIME_IN_MS}
      PASSWORD_SETUP_TOKEN_TIME_IN_MS: ${PASSWORD_SETUP_TOKEN_TIME_IN_MS}
      PASSWORD_SETUP_TOKEN_SECRET: ${PASSWORD_SETUP_TOKEN_SECRET}
      UI_URL: ${UI_URL}
      API_URL: ${API_URL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      RESEND_API_KEY: ${RESEND_API_KEY}
  postgres:
    restart: always
    container_name: school_mgmt_postgres
    image: postgres:13.22-alpine3.22
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB={DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./seed_db:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - school_mgmt_network

volumes:
  postgres_data:

networks:
  school_mgmt_network:
    name: school_mgmt_network
    driver: bridge
